### ISSUE TITLE
Can't build without installing teamengine locally first

### ISSUE THREAD

**Issue by srstsavage** [opengeospatial/ets-sos10#5]
ets-sos10 uses teamengine-core 4.0.5 as a dependency, but teamengine-core isn't available on the [ogc-projects cite Maven repository](https://svn.opengeospatial.org/ogc-projects/cite/maven/org/opengis/cite/teamengine/). The build fails unless I check out the [teamengine project at the 4.0.5 tag](https://github.com/opengeospatial/teamengine/tree/4.0.5) and install locally. Other test suites (e.g. [opengeospatial/ets-wfs11](https://github.com/opengeospatial/ets-wfs11)) also have the same problem.

Seems like all the teamengine modules should be published to the ogc-projects cite Maven repo, and not just the parent?

**Comment by bermud** [comment]
Thank you for letting us know. We are looking into this.

**Comment by bermud** [comment]
@shane-axiom, we are not publishing all teamengine modules and tests to the Maven repo

@rjmartell, can you please clairfy what is being publlished in the Maven repo?
